pipeline {
    agent any
        stages {
            stage("Code Clone") {
                steps{
                    echo "Cloing code from github..!!"
                    git url: "https://github.com/ashubambal/Jenkins-Shared-Library-Projects.git", branch: "master"
                }
            }
            stage("Code Build & Test") {
                steps{
                    script {
                        dir("node-todo-cicd/") {
                            echo "Building the Docker image"
                            sh "docker build -t node-app-demo ."
                        }
                    }
                }
            }
            /*
            stage("Code Push on DockerHub") {
                steps{
                    sh "cd node-todo-cicd/"                     
                    echo "pushing code on dockerhub"
                    withCredentials([usernamePassword(credentialsId:"dockerhub",passwordVariable:"dockerHubPass",usernameVariable:"dockerHubUser")]){
                        sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                        sh "docker tag node-app-demo ${env.dockerHubUser}/node-app-demo:latest"
                        sh "docker push ${env.dockerHubUser}/node-app-demo:latest "
                    }
                }
            }
            stage("Code Deploy") {
                steps{
                    sh "cd node-todo-cicd/" 
                    echo "Deploying code"
                    sh "docker-compose down && docker-compose up -d"
                }
            }
            */
        }
}
